### ISSUE TITLE
[ADD] CSS 과제

### ISSUE THREAD

**Issue by Sleepingoff** [raccoonshome/raccoon#2]
### 주제: fox css 과제

[과제 다운로드 및 제출](https://camp.veamcamp.com/funnycss)

[피그마 링크]( https://www.figma.com/file/XCBWidUFVHNkzrnJ0lDgVR/FOX?type=design&node-id=0%3A1&mode=design&t=oUIEFkDWP2yDuqZW-1)

**Comment by Sleepingoff** [comment]
제출완료

**Comment by Sleepingoff** [comment]
제출 완료!

**Comment by catisverycute** [comment]
제출 완료

**Comment by CreateSong** [comment]
제출 완료

**Comment by haileyja** [comment]
제출완료

**Comment by catisverycute** [comment]
제출완료

**Comment by wooluck210** [comment]
제출 완료

**Comment by gunhee98** [comment]
제출 완료
